#!/usr/bin/env python

import os
import sys


def edit():
    try:    
        f = open(".edirc")
        file = f.read().strip() 
        if file == "":
            print "the edi file is empty"
            sys.exit(1)
        if os.environ.has_key("EDITOR"):
            os.system("$EDITOR " + file)
        else:
            os.system("vim " + file)
    except:
        print "edi is not configured, use edi set file"
    
if __name__ == "__main__":
    if len(sys.argv) == 1:
        edit()
    else:
        if len(sys.argv) == 2 and sys.argv[1] == "--help":
            print "This is edi, usage is:"
            print "* `edi` - opens whatever file edi is configured to use"
            print "* `edi set [file]` - sets edi to use a file"
            
        if len(sys.argv) == 3 and sys.argv[1] == "set":
            f = open(".edirc", "w")
            f.write(sys.argv[2] + "\n")
            f.flush()
            f.close()
